Custom labels for all pods
RasaHQ/rasa-x-helm pull request #108
Opened 2020-11-29 15:32 UTC by orrshilon

* Add `labels` value which is appended to default labels in all pods in the chart

2020-11-30 15:54 UTC, tczekajlo requested changes
@orrshilon Thanks a lot for your first PR in the project 🎉  I've left two small comments 😄

2020-11-30 15:54 UTC, tczekajlo commented on charts/rasa-x/values.yaml
> +  labels: {}
I'd move these fields to the `global` section and change the name to `additionalDeploymentLabels`. The `labels` field in the `rasax` section implies that extra labels are applied only for the rasa-x deployment.

2020-11-30 15:54 UTC, tczekajlo commented on charts/rasa-x/values.yaml
> +  # additional labels can be used to map organizational structures onto system objects
The comment should start with the name of the property that it describes, more: https://helm.sh/docs/chart_best_practices/values/#document-valuesyaml

2020-12-01 08:50 UTC, sara-tagger commented
Thanks for submitting a pull request 🚀 @akelad will take a look at it as soon as possible ✨

2020-12-01 15:03 UTC, tczekajlo approved these changes
LGTM

2020-12-01 15:03 UTC, merged