Add update_rasa_x_version workflow
RasaHQ/rasa-x-helm pull request #116
Opened 2021-01-06 09:24 UTC by HotThoughts

- Get `rasa-x` version tag from DockerHub (the latest version is 0.35.0 at the moment)
- Update `rasa-x` version tag in `Chart.yaml` if the current version is not the latest one by creating a new PR

2021-01-06 13:05 UTC, tczekajlo requested changes

2021-01-06 13:05 UTC, tczekajlo commented on .github/workflows/update_rasa_x_version.yml
> +      - name: Compare latest Rasa X minor with rasa-xhelm version ⏯
```suggestion
      - name: Compare latest Rasa X minor with rasa-x-helm version ⏯
```

2021-01-06 14:44 UTC, tczekajlo requested changes

2021-01-06 14:44 UTC, tczekajlo commented on .github/workflows/update_rasa_x_version.yml
> +          LATEST_RASA_X_MINOR=$(curl -s ${DOCKERHUB_TAGS_URL} | jq -r '.results[].name' | grep -vE 'refs|aws|latest|stable|master|ls|list' | sort -Vr | head -n1 | sed 's/[a-z].*//')
We should use only a stable version.
```suggestion
          LATEST_RASA_X_MINOR=$(curl -s ${DOCKERHUB_TAGS_URL} | jq -r '.results[].name' | grep -vE 'refs|aws|latest|stable|master|ls|list' | sort -Vr | head -n1 | sed 's/[a-z].*//')
```
```suggestion
          LATEST_RASA_X_MINOR=$(curl -s ${DOCKERHUB_TAGS_URL} | jq -r '.results[].name' | grep -vE 'refs|aws|latest|stable|master|ls|list' | sort -Vr | grep -E "^[0-9.]+$" | head -n1')
```

2021-01-07 16:22 UTC, tczekajlo approved these changes
LGTM (I've suggested cosmetic changes)

2021-01-07 16:22 UTC, tczekajlo commented on .github/workflows/update_rasa_x_version.yml
> +
```suggestion
```

2021-01-07 16:22 UTC, tczekajlo commented on .github/workflows/update_rasa_x_version.yml
> +
```suggestion
```

2021-01-08 16:21 UTC, HotThoughts commented
@tczekajlo do you have time to look at [the error](https://github.com/RasaHQ/rasa-x-helm/pull/116/checks?check_run_id=1669134362)?

2021-01-11 11:05 UTC, merged