Use nginx-ingress for k3s
RasaHQ/rasa-x-helm pull request #127
Opened 2021-01-13 16:33 UTC by HotThoughts

2021-01-18 20:36 UTC, tczekajlo commented on .github/deployments/nginx-ingress.yaml
> +apiVersion: extensions/v1beta1
Why do we need it?

2021-01-19 07:47 UTC, HotThoughts commented on .github/deployments/nginx-ingress.yaml
> +apiVersion: extensions/v1beta1
Removed 👍

2021-01-19 09:14 UTC, tczekajlo requested changes

2021-01-19 09:14 UTC, tczekajlo commented on .github/deployments/helmfile.yaml
> +                - /
`No newline at and of file`

2021-01-19 09:14 UTC, tczekajlo commented on .github/deployments/helmfile.yaml
> +                - /
```suggestion
      - rasax:
          disableTelemetry: true
          initialUser:
            password: {{ requiredEnv "INITIAL_USER_PASSWORD" }}
      - duckling:
          enabled: false
      - nginx:
          enabled: false
      - ingress:
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/enable-cors: "true"
          hosts:
            - host: example.test.com
              paths:
                - /
```
You need a few options more

2021-01-19 09:14 UTC, tczekajlo commented on .github/workflows/ci.yml
> +        HOST=$(kubectl get ingress  -o json | jq .items[0].spec.rules[0].host)
```suggestion
        ADDRESS=$(kubectl get ingress -o jsonpath='{.items[0].status.loadBalancer.ingress[0].ip}')
        HOST=$(kubectl get ingress -o jsonpath='{.items[0].spec.rules[0].host}')
```

You don't have to use `jq`, `kubectl` can be used to get a value of a specific path

2021-01-19 15:17 UTC, tczekajlo requested changes

2021-01-19 15:17 UTC, tczekajlo commented on .github/deployments/rasa-x-helmfile.yaml
> +            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
```suggestion
```

We don't use HTTPS for tests

2021-01-22 08:55 UTC, tczekajlo requested changes

2021-01-22 08:55 UTC, tczekajlo commented on .github/workflows/ci.yml
> +    - name: Deploy nginx chart ☕️
```suggestion
    - name: Deploy ingress-nginx ☕️
```

2021-01-22 08:55 UTC, tczekajlo commented on .github/workflows/ci.yml
> +        helmfile -f .github/deployments/nginx-helmfile.yaml sync
```suggestion
        helmfile -f .github/deployments/ingress-nginx-helmfile.yaml sync
```
You have to change the file name as well :)

2021-01-25 17:11 UTC, tczekajlo approved these changes
LGTM 🎖️

2021-01-25 17:25 UTC, merged