check branch name for duplicates
RasaHQ/rasa-x-helm pull request #135
Opened 2021-01-18 15:01 UTC by HotThoughts

2021-01-18 15:11 UTC, HotThoughts commented
Is the error in Lint the chart related to #133?

2021-01-18 15:12 UTC, tczekajlo commented
> Is the error in Lint the chart related to #133?

Yes, it's related.

2021-01-26 09:45 UTC, tczekajlo requested changes

2021-01-26 09:45 UTC, tczekajlo commented on .github/workflows/update_rasa_x_version.yml
> +          BRANCH_NAME=$(curl https://api.github.com/repos/$GITHUB_REPOSITORY/branches | jq '.[].name' | grep -m 1 "bump-rasa-x-version-to-${LATEST_RASA_X_MINOR}")
You don't have to use GH API, I think the `git branch` command should be enough

```
# get all remote branches
git fetch origin

BRANCH_NAME=$(git branch | grep -m 1 "bump-rasa-x-version-to-${LATEST_RASA_X_MINOR}")
```

2021-01-26 14:34 UTC, tczekajlo approved these changes
LGTM 🍎

2021-01-26 14:35 UTC, merged