Add "cache" section to the endpoints.yml
RasaHQ/rasa-x-helm pull request #144
Opened 2021-02-16 10:18 UTC by degiz

As part of https://github.com/RasaHQ/rasa-x/pull/4401 we need to have a new "cache" section in the `endpoints.yml`.

- Add new section to the config map
- Pass REDIS_PASSWORD env variable to the rasa-x pods

2021-02-16 11:04 UTC, degiz commented
@tczekajlo not sure what the checks is failing, is it something that I broke?

2021-02-17 10:47 UTC, wochinge commented
@degiz I think re-running should help 😬 What if users want to separate the Rasa Open Source deployment from the Rasa X deployment and use a separate Redis instance? In my opinion fine to not consider this as part of the first iteration, but I'd still like to discuss potential enterprise requirements.

2021-02-17 10:48 UTC, degiz commented
> but I'd still like to discuss potential enterprise requirements

2021-02-17 10:50 UTC, degiz commented
> but I'd still like to discuss potential enterprise requirements

Thanks for pointing this out! That could be a valid point for the future. Not sure it is a problem now tho, I'd expect the single postgres contrainer to become a problem first.

2021-02-17 10:50 UTC, degiz commented
Also, this PR should be merged only once we release the `0.37` now.

2021-02-17 16:29 UTC, wochinge commented
In my opinion we can merge this right away. Rasa X will ignore it anyway, no?

2021-02-24 15:43 UTC, tczekajlo requested changes
You have to bump up the chart version :)

2021-02-24 16:46 UTC, tczekajlo approved these changes
👍🏻

2021-02-24 16:47 UTC, merged