Add option to specify more than one rabbit queue
RasaHQ/rasa-x-helm pull request #198
Opened 2021-05-26 13:55 UTC by melindaloubser1

- Add template to include list of multiple rabbit queues as is possible in a docker-compose deployment for adding e.g. a queue for ELK to consume from

2021-05-26 13:56 UTC, melindaloubser1 commented on charts/rasa-x/templates/rasa-deployments.yaml
> -          value: "{{ $.Values.rasa.rabbitQueue }}"
This was a duplicate I added accidentally 4 months ago

2021-05-26 14:43 UTC, desmarchris approved these changes

2021-05-26 15:29 UTC, tczekajlo approved these changes
🎖️

2021-05-26 15:30 UTC, tczekajlo requested changes

2021-05-26 15:30 UTC, tczekajlo commented on charts/rasa-x/Chart.yaml
> +version: "1.11.1"
```suggestion
version: "1.11.0"
```
We add a new feature, not a fix :D

2021-05-27 08:36 UTC, tczekajlo approved these changes
🎖️

2021-05-27 08:36 UTC, merged