removed '@' from the password validation schema
RasaHQ/rasa-x-helm pull request #223
Opened 2021-07-28 12:06 UTC by RASADSA

fix for 
https://github.com/RasaHQ/rasa-x-helm/issues/221

2021-07-28 13:14 UTC, RASADSA commented
@tczekajlo would merge it since this is a deployment timeout most likely imposed due rate limiting and this is one char :)

2021-07-28 14:04 UTC, tczekajlo commented
Can you bump the chart version to `2.0.3` - https://github.com/RasaHQ/rasa-x-helm/blob/main/charts/rasa-x/Chart.yaml#L4 and add a changelog annotation? - https://github.com/RasaHQ/rasa-x-helm/blob/main/charts/rasa-x/Chart.yaml#L43-L45

🙏🏻

2021-07-29 09:30 UTC, tczekajlo requested changes

2021-07-29 09:30 UTC, tczekajlo commented on charts/rasa-x/Chart.yaml
> +      description: added @ char to the not allowed chars for the rabbit password in helm chart values
No newline at end of file :)

2021-07-29 09:30 UTC, tczekajlo commented on charts/rasa-x/Chart.yaml
>        description: Move the egress-from-rasa-x-to-https network policy out of if condition
```suggestion
```

2021-07-29 12:40 UTC, tczekajlo approved these changes
LGTM 🎖️

2021-08-20 07:05 UTC, tczekajlo requested changes

2021-08-20 07:05 UTC, tczekajlo commented on charts/rasa-x/Chart.yaml
>        description: Add an option to define hostNetwork and DNS policy for the rasa-x deployment
```suggestion
```

2021-08-20 07:05 UTC, tczekajlo commented on charts/rasa-x/Chart.yaml
>  version: "2.3.0"
```suggestion
version: "2.3.1"
```

2021-08-20 08:40 UTC, RASADSA commented
where is my mind... thx @tczekajlo 
![image](https://user-images.githubusercontent.com/86777724/130206070-f9805739-13ae-4580-a7dd-0b4345330016.png)

2021-08-20 09:12 UTC, tczekajlo approved these changes

2021-08-24 11:27 UTC, merged